name: 'hello-world-action-milan-test'
description: 'This action prints "Hello World"'
author: 'milan-trayt'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: 'composite'
  steps:
    - run: npm install && node index.js
      shell: bash
      
